init: Initial Release

diff --git a/gh-wclone b/gh-wclone
--- a/gh-wclone
+++ b/gh-wclone
@@ -1,35 +1,39 @@
 #!/usr/bin/env bash
 set -e
 
-echo "Hello gh-wclone!"
+# Get the current directory
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-# Snippets to help get started:
+repo_name="$1"
+clone_path="$2"
 
-# Determine if an executable is in the PATH
-# if ! type -p ruby >/dev/null; then
-#   echo "Ruby not found on the system" >&2
-#   exit 1
-# fi
+if [ -z "$repo_name" ]; then
+  echo "Usage: $0 <repo_name>"
+  exit 1
+fi
 
-# Pass arguments through to another command
-# gh issue list "$@" -R cli/cli
+# Get Repo Name to clone
+repo_name=$(echo $repo_name | sed 's/.*github.com\///g') # Remove everything before github.com
+repo_name=$(echo $repo_name | sed 's/\.git//g') # Remove .git if present
+repo_name=$(echo $repo_name | sed 's/.*\///g') # Remove everything before the last slash
 
-# Using the gh api command to retrieve and format information
-# QUERY='
-#   query($endCursor: String) {
-#     viewer {
-#       repositories(first: 100, after: $endCursor) {
-#         nodes {
-#           nameWithOwner
-#           stargazerCount
-#         }
-#       }
-#     }
-#   }
-# '
-# TEMPLATE='
-#   {{- range $repo := .data.viewer.repositories.nodes -}}
-#     {{- printf "name: %s - stargazers: %v\n" $repo.nameWithOwner $repo.stargazerCount -}}
-#   {{- end -}}
-# '
-# exec gh api graphql -f query="${QUERY}" --paginate --template="${TEMPLATE}"
+echo "🚀 Setting up $repo_name 🚀"
+
+# parse last folder name
+FOLDER_NAME=${PWD##*/}
+
+REPO_ID=$(gh api graphql -F owner="$FOLDER_NAME" -F name="$repo_name" -f query='
+    query($name: String!, $owner: String!) {
+      repository(owner: $owner, name: $name) {
+        id
+      }
+    }
+' --jq ".data.repository.id")
+
+if [ -z "$REPO_ID" ]; then
+  echo "🚨 Repo not found 🚨"
+  exit 1
+fi
+
+# Clone the repo
+gh repo clone "$FOLDER_NAME/$repo_name" $clone_path -- --depth=1
